---
# Retrieve inventory from a deployed CI arcus environment by reversing .stackhpc/inventory/hooks/pre.yml
# Usage example:
#   ansible-playbook ansible/ci/retrieve_inventory.yml -e cluster_prefix=slurmci-RL8-1030
#
- hosts: localhost
  become: false
  gather_facts: false
  vars:
    cluster_prefix: "{{ undef(hint='cluster_prefix must be defined') }}" # e.g. slurmci-RL8-1030
    ci_vars_file: "{{ appliances_environment_root + '/tofu/' + lookup('env', 'CI_CLOUD') }}.tfvars"
    network_regex: 'network = "(.+)"$'
    cluster_network: "{{ lookup('ansible.builtin.file', ci_vars_file) | ansible.builtin.regex_search(network_regex, '\\1', multiline=True) }}"
  tasks:
    - name: Get control host IP
      ansible.builtin.set_fact:
        control_ip: "{{ (lookup('pipe', 'openstack server show -f json ' + cluster_prefix + '-control') | from_json)['addresses'][cluster_network][0] }}"
    - name: Add host into in-memory inventory
      ansible.builtin.add_host:
        name: cluster_control
        groups: control
        ansible_host: "{{ control_ip }}"

- hosts: control
  become: true
  gather_facts: false
  tasks:
    - ansible.builtin.fetch:
        src: "/etc/ci-config/{{ item | basename }}"
        dest: "{{ item }}"
        flat: true
      loop:
        - "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/inventory/hosts.yml"
        - "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/inventory/group_vars/all/secrets.yml"
        - "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/inventory/group_vars/all/test_user.yml"
