{
 "title": "OnDemand",
 "description": "Dashboard for OnDemand Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "label_values(ondemand_active_puns, environment)"
   },
   {
    "name": "instance",
    "query": "label_values(ondemand_active_puns{environment=~\"$environment\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "OnDemand Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active PUNs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ondemand_active_puns{environment=~\"$environment\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active PUNs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ondemand_active_puns{environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unique Client Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ondemand_unique_client_connections{environment=~\"$environment\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Unique Websocket Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ondemand_unique_websocket_clients{environment=~\"$environment\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "OnDemand Passenger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Passenger App Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ondemand_passenger_app_count{environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Passenger App CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ondemand_passenger_app_cpu_percent{environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Passenger App Memory %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ondemand_passenger_app_real_memory_bytes{environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "Passenger App Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ondemand_passenger_app_requests_total{environment=~\"$environment\", instance=~\"$instance\"}[15m])",
     "legendFormat": "{{instance}} - {{app}}"
    }
   ]
  },
  {
   "title": "OnDemand Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Apache Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ondemand_unique_client_connections{environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - client connections"
    },
    {
     "expr": "ondemand_unique_websocket_clients{environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - websocket connections"
    }
   ]
  },
  {
   "title": "OnDemand Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OnDemand Apps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ondemand_node_apps{environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - NodeJS"
    },
    {
     "expr": "ondemand_rack_apps{environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Rack"
    }
   ]
  },
  {
   "title": "OnDemand PUN Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OnDemand PUN CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(ondemand_pun_cpu_time{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "OnDemand PUN Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ondemand_pun_memory_percent{environment=~\"$environment\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}