{
 "title": "OpenHPC Slurm",
 "description": "Mashup of openhpc dashboard with slurm-stats",
 "time": { "from": "now-25h", "to": "now-23h" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_cpu_seconds_total, job)"
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(node_cpu_seconds_total{job=~\"node\"}, env)"
   },
   { "name": "host_filter", "label": "Host Filter Regex", "query": ".+" },
   {
    "name": "instance",
    "query": "label_values(node_cpu_seconds_total{job=~\"node\", env=~\"$env\", instance=~\"$host_filter\"}, instance)"
   },
   {
    "name": "device",
    "label": "infiniband device",
    "query": "label_values(node_infiniband_info{job=~\"node\"}, device)"
   },
   { "name": "job_id", "label": "Job ID" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage (system)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": " node_cpu_system_seconds:record{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU usage (user)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": " node_cpu_user_seconds:record{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Frequency Min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": " node_cpu_scaling_frequency_hertz_min:record{instance=~\"$instance\"}",
     "legendFormat": "Min {{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Frequency Max",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": " node_cpu_scaling_frequency_hertz_max:record{instance=~\"$instance\"}",
     "legendFormat": "Max {{ instance }}"
    }
   ]
  },
  {
   "title": "System stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory  used as a percentage of total",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100 * node_memory_MemAvailable_bytes{job=~\"node\", instance=~\"$instance\"} / node_memory_MemTotal_bytes{job=~\"node\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU usage (iowait and other)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": " node_cpu_iowait_seconds:record{instance=~\"$instance\"}"
    },
    {
     "expr": " node_cpu_other_seconds:record{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU throttles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_cpu_core_throttles_total{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Infiniband",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Outbound Infiniband Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_transmitted_bytes_total{job=~\"$job\",instance=~\"$instance\",device=~\"$device\"}[60s])\n",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Inbound Infiniband Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_received_bytes_total{job=~\"$job\",instance=~\"$instance\",device=~\"$device\"}[60s])",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Outbound Infiniband Packets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_infiniband_port_packets_transmitted_total{job=~\"$job\",instance=~\"$instance\",device=~\"$device\"}[60s])\n",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Inbound Infiniband Packets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_infiniband_port_packets_received_total{job=~\"$job\",instance=~\"$instance\",device=~\"$device\"}[60s])",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Normalized XmitWait [ticks] = ∆XmitWait / ∆XmitPackets",
   "type": "timeseries",
   "description": "A value greater than ten should be considered congested",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(node_infiniband_port_transmit_wait_total{job=\"node\",instance=~\"$instance\"}[1m]) / increase(node_infiniband_port_packets_transmitted_total{job=\"node\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ instance }} {{ device }} {{  port }}"
    }
   ]
  },
  {
   "title": "IB Link problems",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_infiniband_port_discards_transmitted_total{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "discards {{ instance }} {{ device }} {{  port }}"
    },
    {
     "expr": "node_infiniband_link_error_recovery_total{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "error recovery  {{ device }} {{  port }}"
    },
    {
     "expr": "rate(node_infiniband_link_downed_total{job=~\"$job\",instance=~\"$instance\"}[1m])",
     "legendFormat": "link down {{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Network Traffic (transmit)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"$job\",instance=~\"$instance\"}[60s])*8",
     "legendFormat": "{{instance}} {{device}}_out"
    }
   ]
  },
  {
   "title": "Network Traffic (receive)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"$job\",instance=~\"$instance\"}[60s])*8",
     "legendFormat": "{{instance}} {{device}}_in"
    }
   ]
  }
 ]
}