---

# Want to run specific playbooks from osc.ood role so need to replicate its
# tasks/main:include_vars but with this vars defaults overriding them:
- name: Include distribution variables
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/roles/osc.ood/vars/Rocky/{{ ansible_distribution_major_version }}.yml"

- name: Set osc.ood variables from this role's defaults if no overriding inventory var
  ansible.builtin.set_fact:
  # NB: When condition is important - some configurations require undefined vars
    "{{ item.key }}": "{{ lookup('vars', item.key, default=item.value) }}"
  loop: "{{ openondemand_osc_ood_defaults | dict2items }}"
  when: (item.key in hostvars[inventory_hostname]) or (item.value)

# if using PAM auth we need apache installed but NOT started so split the osc.ood role up:
- ansible.builtin.include_role:
    name: osc.ood
    tasks_from: install-package.yml
    vars_from: "Rocky/{{ ansible_distribution_major_version }}.yml"
  when: appliances_mode != 'configure'
  # can't set vars: from a dict hence the workaround above

- name: Install Apache PAM module
  ansible.builtin.dnf:
    name: mod_authnz_pam
  when:
    - openondemand_auth | lower == 'basic_pam'
    - appliances_mode != 'configure'

- name: Configure PAM
  ansible.builtin.include_tasks:
    file: pam_auth.yml
  when:
    - openondemand_auth | lower == 'basic_pam'
    - appliances_mode != 'build'

- name: Install certbot
  ansible.builtin.dnf:
    name:
      - certbot
      - python3-certbot-apache
  when:
    - openondemand_certbot | bool
    - appliances_mode != 'configure'

- ansible.builtin.include_role:
    name: osc.ood
    tasks_from: install-apps.yml
  when: appliances_mode != 'configure'

- ansible.builtin.include_tasks:
    file: configure.yml
  when: appliances_mode != 'build'

- name: Generate Let's Encrypt certificate
  # A note on ordering: Running certbot --apache will start apache if necessary.
  # If this task is moved before the ondemand startup and the LE cert paths are
  # set in `openondemand_ssl_cert{,.key}`, then apache will fail to start as
  # the cert/key do not exist. The cleanest way to break the cycle is to simply
  # start ondemand first, and always have the self-signed certs defined in the
  # ondemand configuration.
  ansible.builtin.command:
    cmd: >
      certbot
        --non-interactive --agree-tos --verbose
        --apache --no-eff-email
        --domains {{ openondemand_servername }}
        {% if openondemand_certbot_staging | bool %}
        --staging
        {% endif %}
        --email {{ openondemand_certbot_email }}
  register: _openondemand_certbot
  changed_when: "'Certificate not yet due for renewal' not in _openondemand_certbot.stdout"
  when:
    - openondemand_certbot | bool
    - appliances_mode != 'build'
