---
- name: Ensure /home symlink exists
  hosts: cluster
  become: true
  tasks:
    # Symlink /home to /storage/simple/users
    - ansible.builtin.file:
        dest: /home
        src: /storage/simple/users
        follow: false
        force: true
        group: root
        owner: root
        state: link

- name: Ensure /nfs symlink exists
  hosts: cluster
  become: true
  tasks:
    # Symlink /nfs to /storage/replicated/nfs
    - ansible.builtin.file:
        dest: /nfs
        src: /storage/replicated/nfs
        follow: false
        force: true
        group: root
        owner: root
        state: link
