---
- name: Set timezone to Europe/Paris
  hosts: cluster
  become: true
  tasks:
    - community.general.timezone:
        name: Europe/Paris

- name: Create NFS symlinks
  hosts: cluster:!builder
  become: true
  tasks:
    # Symlink /home to /storage/simple/users
    - name: Ensure /home symlink exists
      ansible.builtin.file:
        dest: /home
        src: /storage/simple/users
        follow: false
        force: true
        group: root
        owner: root
        state: link
    - name: Ensure /nfs symlink exists
      ansible.builtin.file:
        dest: /nfs
        src: /storage/replicated/nfs
        follow: false
        force: true
        group: root
        owner: root
        state: link
    - name: Ensure /trinity exists
      ansible.builtin.file:
        path: /trinity
        owner: root
        group: root
        state: directory

    - name: Ensure /trinity/shared exists
      ansible.builtin.file:
        dest: /trinity/shared
        src: /storage/replicated/nfs
        follow: false
        force: true
        group: root
        owner: root
        state: link

- name: Ensure /var/lib/home directory exists
  hosts: cluster
  become: true
  tasks:
    - ansible.builtin.file:
        path: /var/lib/home
        owner: root
        group: root
        state: directory

- name: Configure NFS v4 identity mapping
  hosts: cluster
  become: true
  tasks:
    - ansible.builtin.lineinfile:
        path: /etc/idmapd.conf
        regexp: '^#Domain = local.domain.edu$'
        line: 'Domain = cluster'

- name: Configure MODULEPATH with local modules
  hosts: cluster:!builder
  become: true
  tasks:
    - name: Ensure /etc/profile.d/zzz-io.sh exists
      ansible.builtin.file:
        path: /etc/profile.d/zzz-io.sh
        owner: root
        group: root
        state: touch
    - name: Set MODULEPATH in /etc/profile.d/zzz-io.sh
      ansible.builtin.lineinfile:
        path: /etc/profile.d/zzz-io.sh
        regexp: '^export MODULEPATH.*'
        line: 'export MODULEPATH=$MODULEPATH:/trinity/shared/modulefiles/modulegroups:/trinity/shared/modulefiles/CV-standard:/trinity/shared/modulefiles/local'

- name: Configure Postfix
  hosts: control
  become: true
  tasks:
    - name: Set Postfix myhostname configuration
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        line: 'myhostname = {{ inventory_hostname }}.meso.umontpellier.fr'

    - name: Set Postfix myorigin configuration
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        line: 'myorigin = $myhostname'

    - name: Set Postfix relayhost configuration
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        line: 'relayhost = smtp.meso2'

    - name: Set Postfix sender_canonical_maps configuration
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        line: 'sender_canonical_maps = regexp:/etc/postfix/sender_canonical'

    - name: Create Postfix sender_canonical file
      ansible.builtin.copy:
        content: '/.*/  io-no-reply@umontpellier.fr'
        dest: /etc/postfix/sender_canonical

    - name: Create Postfix lookup table
      command: postmap /etc/postfix/sender_canonical

    - name: Ensure Postfix service is enabled and started
      ansible.builtin.systemd:
        name: postfix
        enabled: true
        state: started

- name: Allow administrators to use sudo
  hosts: cluster
  become: true
  tasks:
    - name: Create /etc/sudoers.d/io-admins
      copy:
        content: |
          %stackhpc   ALL=(ALL)       ALL
          dehneg      ALL=(ALL)       ALL
          dernatr     ALL=(ALL)       ALL
          larreure    ALL=(ALL)       ALL
          omsj        ALL=(ALL)       ALL
          pitollatb   ALL=(ALL)       ALL
        dest: /etc/sudoers.d/io-admins
        validate: '/usr/sbin/visudo -csf %s'

- name: Create GNU Guix synlinks
  hosts: cluster:!builder
  become: true
  tasks:
    - name: Ensure /var/guix symlink exists
      ansible.builtin.file:
        dest: /var/guix
        src: /storage/simple/guix/var
        follow: false
        force: true
        group: root
        owner: root
        state: link
    - name: Ensure /gnu symlink exists
      ansible.builtin.file:
        dest: /gnu
        src: /storage/simple/guix/gnu
        follow: false
        force: true
        group: root
        owner: root
        state: link
    - name: Ensure /usr/local/bin/guix exists
      ansible.builtin.file:
        dest: /usr/local/bin/guix
        src: /var/guix/profiles/per-user/root/current-guix/bin/guix
        follow: false
        force: true
        group: root
        owner: root
        state: link
    - name: Ensure /var/log/guix exists
      ansible.builtin.file:
        dest: /var/log/guix
        src: /storage/simple/guix/log
        follow: false
        force: true
        group: root
        owner: root
        state: link
    - name: Create /etc/profile.d/guix.sh
      copy:
        content: |
          GUIX_DAEMON_SOCKET="guix://guix.meso2:44146"
          export GUIX_DAEMON_SOCKET

          GUIX_LOCPATH=/var/guix/profiles/per-user/root/guix-profile/lib/locale
          export GUIX_LOCPATH

          # Here we must use a valid locale name.  Try "ls $GUIX_LOCPATH/*"
          # to see what names can be used.
          #LC_ALL=C.UTF-8
          #export LC_ALL

          for GUIX_PROFILE in "$HOME/.config/guix/current" "$HOME/.guix-profile"
          do
            if [ -f "$GUIX_PROFILE/etc/profile" ]; then
              . "$GUIX_PROFILE/etc/profile"
            fi
          done
        dest: /etc/profile.d/guix.sh
