flavor = "general.v1.small"
use_blockstorage_volume = true
volume_size = 15 # GB
image_disk_format = "qcow2"
networks = ["e2b9e59f-43da-4e1c-b558-dc9da4c0d738"] # stackhpc-ipv4-geneve
ssh_keypair_name = "slurm-app-ci"
ssh_private_key_file = "~/.ssh/id_rsa"
ssh_bastion_username = "slurm-app-ci"
ssh_bastion_host = "185.45.78.150"
ssh_bastion_private_key_file = "~/.ssh/id_rsa"