---

- name: Create /etc/openstack
  ansible.builtin.file:
    path: /etc/openstack
    state: directory
    owner: slurm
    group: root
    mode: u=rX,g=rwX

- name: Write clouds.yaml
  ansible.builtin.copy:
    content: "{{ {'clouds': {'openstack': _rebuild_clouds_yaml.clouds[rebuild_clouds_key]}} | to_nice_yaml(indent=2) }}"
    dest: /etc/openstack/clouds.yaml
    owner: slurm
    group: root
    mode: u=r,g=rw
  vars:
    _rebuild_clouds_yaml: "{{ lookup('file', rebuild_clouds_path) | from_yaml }}"
