---
# ignore rules for grype, with justification
ignore:
# NOTE(m-bull): Affects the the deepdiff Python package bundled with the
# netbox.netbox Ansible collection. This package is never actually installed,
# and only appears in the netbox.netbox poetry.lock file, so it is safe to ignore.
  - vulnerability: CVE-2025-58367

# GOARCH=wasm GOOS=js is not used
  - vulnerability: CVE-2021-38297
    package:
      location: /usr/local/bin/node_exporter
  - vulnerability: CVE-2021-38297
    package:
      location: /usr/local/bin/prometheus
  - vulnerability: CVE-2021-38297
    package:
      location: /usr/local/bin/promtool


# will be masked at runtime
# FIXME: could cleanup better!
# eg /tmp/prometheus-2.27.0.linux-amd64/prometheus
  - package:
      location: "/tmp/**"

# go crypto/tls vulnerability: programs not used with TLS
  - vulnerability: CVE-2025-68121
    package:
      location: /usr/bin/ondemand_exporter
  - vulnerability: CVE-2025-68121
    package:
      location: /usr/bin/prometheus-slurm-exporter
  - vulnerability: CVE-2025-68121
    package:
      location: /usr/local/bin/node_exporter
  - vulnerability: CVE-2025-68121
    package:
      location: "/usr/local/bin/prometheus"
  - vulnerability: CVE-2025-68121
    package:
      location: "/usr/local/bin/promtool"
  - vulnerability: CVE-2025-68121
    package:
      location: "/usr/sbin/ondemand-dex"
  - vulnerability: CVE-2025-68121
    package:
      location: "/usr/sbin/ondemand-dex-session"
  - vulnerability: CVE-2025-68121
    package:
      location: "/usr/share/grafana/bin/grafana"
  - vulnerability: CVE-2025-68121
    package:
      location: "/usr/share/grafana/bin/grafana-cli"
  - vulnerability: CVE-2025-68121
    package:
      location: "/usr/share/grafana/bin/grafana-server"
  - vulnerability: CVE-2025-68121
    package:
      location: /var/lib/podman/.local/share/containers/storage/overlay/b51397a6db0ae651df3ffd51be823f98a26ab18ac7033847fedbac792798ae18/diff/usr/share/filebeat/filebeat
  - vulnerability: CVE-2025-68121
    package:
      location: /var/lib/podman/.local/share/containers/storage/overlay/efeebaada56fcf04784f6d67852667327a8e50d18bbf9aea6d3556865e894f59/diff/usr/local/bin/gosu

#  go crypto/tls vulnerability: programs used with trusted TLS servers
  - vulnerability: CVE-2025-68121
    package:
      location: /usr/local/bin/alertmanager
  - vulnerability: CVE-2025-68121
    package:
      location: /var/lib/grafana/plugins/grafana-opensearch-datasource/gpx_opensearch-datasource_linux_amd64

# system dep, what can we do?
  - vulnerability: CVE-2025-68121
    package:
      name: podman
  - vulnerability: CVE-2025-68121
    package:
      location: /usr/bin/podman
  - vulnerability: CVE-2025-68121
    package:
      location: "/usr/libexec/podman/**"
  - vulnerability: CVE-2025-68121  # ondemand dep
    package:
      location: "/usr/bin/rclone"

# go crypto/tls vulnerability: programs run by users not admins
  - vulnerability: CVE-2025-68121
    package:
      location: "/usr/bin/apptainer"
  - vulnerability: CVE-2025-68121
    package:
      location: "/usr/libexec/apptainer/**"
  - vulnerability: CVE-2025-68121
    package:
      location: "/usr/libexec/apptainer/**"

# programs not run
  - package:
      location: /var/www/ood/apps/sys/dashboard/node_modules/@esbuild/linux-x64/bin/esbuild
  - package:
      location: /usr/lib/rstudio-server/bin/quarto/bin/tools/x86_64/esbuild

# Python 2.7 vulnerabilities in filebeat and opensearch ignored: python not used at runtime
# CVE-2014-4650 CGIHTTPServer module in Python 2.7.5, in filebeat and opensearch images
# CVE-2016-0718, CVE-2016-9063 Expat
# CVE-2017-1000158 integer overflow in the PyString_DecodeEscape
# CVE-2018-1000802 Command Injection vulnerability in shutil
  - package: # filebeat
      location: /var/lib/podman/.local/share/containers/storage/overlay/174f5685490326fc0a1c0f5570b8663732189b327007e47ff13d2ca59673db02/diff/usr/bin/python2.7
  - package: # filebeat
      location: /var/lib/podman/.local/share/containers/storage/overlay/174f5685490326fc0a1c0f5570b8663732189b327007e47ff13d2ca59673db02/diff/usr/lib64/libpython2.7.so.1.0
  - package: # filebeat
      location: /var/lib/podman/.local/share/containers/storage/overlay/6b0b788550f0cdfdceded05ec82b17c5bd3801b6a7795fecb4a18d1103d5d548/diff/usr/bin/python2.7
  - package: # filebeat
      location: /var/lib/podman/.local/share/containers/storage/overlay/6b0b788550f0cdfdceded05ec82b17c5bd3801b6a7795fecb4a18d1103d5d548/diff/usr/lib64/libpython2.7.so.1.0
  - package: # opensearch
      location: /var/lib/podman/.local/share/containers/storage/overlay/6042fe893e2746bb7637efe59d35909d895c9060b43950db261e692ad3dfb834/diff/usr/bin/python2.7
  - package: # opensearch
      location: /var/lib/podman/.local/share/containers/storage/overlay/6042fe893e2746bb7637efe59d35909d895c9060b43950db261e692ad3dfb834/diff/usr/lib64/libpython2.7.so.1.0
