line-length = 120

# Store the cache in a temporary location
cache-dir = "/tmp/.ruff_cache"

# as for azimuth-cloud python repos, e.g. azimuth-caas-operator
[lint]
# FIXME: temporary disabling azimuth config, only selecting ruff default
select = ["E4", "E7", "E9", "F"]
# select = [
#     # pycodestyle
#     "E",
#     # Pyflakes
#     "F",
#     # flake8-builtins
#     "A",
#     # Ruff rules
#     "RUF",
#     # flake8-async
#     "ASYNC",
#     # pyupgrade
#     "UP",
#     # tidy imports
#     "TID",
#     # sorted imports
#     "I",
#     # check complexity
#     "C90",
#     # TODO: fix pep8 naming
#     # "N",
#     # pylint rules
#     "PLE",
#     "PLW",
# ]
ignore = [
    "UP017", # remove and fix once CI not running 3.10 tests
]
# Disable E402 for ansible/library modules where imports may come after docstrings
per-file-ignores = {
    "ansible/library/*.py" = ["E402"],
}