#!/usr/bin/env python3
"""
SSH to a cluster host using Ansible connection properties from inventory,
configuration, environment vars etc.

Usage:
   ansible-ssh PATTERN

where PATTERN can be any of:
    - host e.g. mycluster-login-0
    - group e.g. login
    - group[index] e.g. compute[0]
"""

import re
import os
import shlex
import subprocess
import sys

if __name__ == "__main__":
    no_known_hosts = "-n" in sys.argv
    if sys.argv[-1] in (sys.argv[0], "-n"):
        print(__doc__, file=sys.stderr)
        sys.exit(-1)

    pattern = sys.argv[-1]
    ansible_cmd = ["ansible", pattern, "-a", "hostname", "-vvvv", "--timeout", "1"]
    try:
        output = subprocess.check_output(ansible_cmd, text=True)
    except subprocess.CalledProcessError:
        msg = "[ERROR]: ansible exited in error"
        print(msg, file=sys.stderr)
        sys.exit(-1)
    if not output:
        sys.exit(1)
    ssh_cmd = None
    for line in output.splitlines():
        match = re.match(r".*SSH: EXEC (.*) '/bin/sh", line)
        if match is not None:
            if len(match.groups()) != 1:
                sys.exit("ERROR: Could not extract SSH command from output")
            ssh_cmd = match.groups()[0]
            # strip out verbosity flags
            ssh_cmd = re.sub(r"\s+-v+\b", "", ssh_cmd)
            # strip out our timeout arg
            ssh_cmd = re.sub(r"-o ConnectTimeout=1", "", ssh_cmd)
            break
    if ssh_cmd is None:
        sys.exit("ERROR: Did not find SSH command in output")
    cmd = shlex.split(ssh_cmd)

    print(f"[INFO]: Running: {subprocess.list2cmdline(cmd)}")
    os.execvp(cmd[0], cmd)
