#!/usr/bin/env python3

# This tool allows you to ssh into a host using the ansible inventory.
# Example: ansible-ssh prd-compute-0

import sys
import subprocess
import shlex
import json
import os

if __name__ == "__main__":
    if len(sys.argv) < 2:
        msg = (f"Usage: {sys.argv[0]} <inventory_hostname>")
        print(msg, file=sys.stderr)
        sys.exit(-1)

    # Quote to prevent shell injection
    host = shlex.quote(sys.argv[1])
    
    # Define templated command:
    jinja_template = "ssh {{ ansible_user }}@{{ ansible_ssh_host }} -i {{ ansible_ssh_private_key_file }} {{ ansible_ssh_common_args | default('') }}"
    
    # Run via ansible:
    json_arg = json.dumps({"msg":jinja_template})
    ansible_cmd = f"ansible {host} -m debug -a '{json_arg}'"
    print("ansible_cmd:", ansible_cmd)
    output = subprocess.check_output(ansible_cmd, text=True, shell=True)
    
    # Process command output:
    _, body = output.split(':', 1)
    ssh_cmd = body.splitlines()[0].strip().strip('"')
    print('ssh_cmd:', ssh_cmd)
    shell_cmd = shlex.split(ssh_cmd)
    
    # Run shell:
    print(f"[INFO]: Running: { subprocess.list2cmdline(shell_cmd)}")
    os.execvp(shell_cmd[0], shell_cmd)
