---
hpctests_user: "{{ ansible_user }}"
hpctests_group: "{{ hpctests_user }}"
hpctests_rootdir: "/home/{{ hpctests_user }}/hpctests"
hpctests_pre_cmd: ""
hpctests_pingmatrix_modules:
  - gnu12
  - openmpi4
hpctests_pingpong_modules:
  - gnu12
  - openmpi4
  - imb
hpctests_pingpong_plot: true
hpctests_hpl_modules:
  - gnu12
  - openmpi4
  - openblas
hpctests_outdir: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/hpctests"
hpctests_ucx_net_devices: all
hpctests_hpl_version: "2.3"
hpctests_hpl_NB: 192
hpctests_hpl_mem_frac: 0.3
hpctests_hpl_arch: linux64
# hpctests_nodes:
# hpctests_partition:
# hpctests_account:
# hpctests_qos:
hpctests_cuda_compute_level: 8.0
hpctests_gpuburn_node_chunk_percent: 10  # seems safe to run on 10% of the nodes by default
hpctests_gpuburn_minutes: 1
hpctests_gpuburn_version: "671f4be92477ce01cd9b536bc534a006dbee058f" # latest commit in master at this time
