variable "environment_root" {
  type = string
  description = "Path to environment root, automatically set by activate script"
}

module "cluster" {
  source = "../../site/tofu/"

  cluster_name = "io"
  cluster_networks = [
    {
      network = "netapp"
      subnet = "netapp"
    }
  ]
  key_pair = "rally"
  control_node_flavor = "m1.xlarge"
  control_ip_addresses = {
    "netapp" = "192.168.52.3",
  }
  login = {
    # Arbitrary group name for these login nodes
    interactive = {
      nodes = [
        "login-01",
        "login-02",
      ]
      flavor = "m1.xlarge"
      fip_addresses = [
        "194.199.232.101",
        "194.199.232.102",
      ]
    }
  }
  # RL9.4 + OFED 23.10-3.2.2.0 + SSSD + local packages
  cluster_image_id = "597cbd0f-6060-4a1c-a7e3-afd9914a8cc8"
  compute = {
    # Group name used for compute node partition definition
    cpu = {
      flavor = "baremetal"
      nodes = [
        "io-cpu-01",
        "io-cpu-02",
        "io-cpu-03",
        "io-cpu-04",
        "io-cpu-05",
        "io-cpu-06",
        "io-cpu-07",
        "io-cpu-08",
        "io-cpu-09",
        "io-cpu-10",
        "io-cpu-11",
        "io-cpu-12",
        "io-cpu-13",
        "io-cpu-14",
        "io-cpu-15",
        "io-cpu-16",
        "io-cpu-17",
        "io-cpu-18",
        "io-cpu-19",
        "io-cpu-20",
        "io-cpu-21",
        "io-cpu-22",
        "io-cpu-23",
        "io-cpu-24",
        "io-cpu-25",
        "io-cpu-26",
        "io-cpu-27",
        "io-cpu-28",
        "io-cpu-29",
        "io-cpu-30",
        "io-cpu-31",
        "io-cpu-32",
      ]
      extra_networks = [
        {
          network = "infiniband"
          subnet = "infiniband"
          no_security_groups = true
        }
      ]
      match_ironic_node = true
      use_ironic_node_name = true
      vnic_types = {
        netapp = "baremetal"
        infiniband = "baremetal"
      }
    }
#    gpu = {
#      flavor = "baremetal-gpu"
#      # RL9.4 + OFED 23.10-3.2.2.0 + SSSD + CUDA 12.8
#      image_id = "ec98d90f-6f38-47cb-831b-449892ef116c"
#      nodes = [
#        "io-gpu-01",
#        "io-gpu-02",
#        "io-gpu-03",
#        "io-gpu-04",
#        "io-gpu-05",
#        "io-gpu-06",
#      ]
#      extra_networks = [
#        {
#          network = "infiniband"
#          subnet = "infiniband"
#          no_security_groups = true
#        }
#      ]
#      match_ironic_node = true
#      use_ironic_node_name = true
#      vnic_types = {
#        netapp = "baremetal"
#        infiniband = "baremetal"
#      }
#    }
  }

  environment_root = var.environment_root

#  # We manually populate this to add GRES. See environments/site/inventory/group_vars/all/partitions-manual.yml.
#  autogenerated_partitions_enabled = false
}
