---
appliances_extra_packages_other:
  # Required to run CUDA samples
  - "{{ 'cuda-toolkit' if 'cuda' in group_names }}"
  - cmake
  # Packages requested by local operators
  - clustershell
  - dos2unix
  - emacs
  - gnupg
  - iftop
  - iotop
  - multitail
  - nethogs
  - nmon
  - s-nail
  - telnet
  - traceroute
  - tree
  - vim
  # Extra packages required for Open OnDemand SSL
  - certbot
  - python3-certbot-apache
