# Generated by cookiecutter terraform to provide a working example environment:

# Define Slurm partitions:
openhpc_slurm_partitions:
%{for type_name, type_descr in compute_types ~}
    - name: ${type_name}
%{ endfor ~}
