---
- name: Ensure directories exist
  ansible.builtin.file:
    path: "/etc/ansible-init/playbooks/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - templates
    - files
    - library
    - filter_plugins
    - tasks
    - roles

- name: Prepare Inject files from roles
  delegate_to: localhost
  changed_when: true
  ansible.builtin.shell: |
    rm -rf __tmp_inject_files
    mkdir -p \
      __tmp_inject_files/files \
      __tmp_inject_files/roles \
      __tmp_inject_files/tasks \
      __tmp_inject_files/templates
    cp \
      roles/resolv_conf/templates/resolv.conf.j2 \
      roles/stackhpc.os-manila-mount/templates/ceph.conf.j2 \
      roles/stackhpc.os-manila-mount/templates/ceph.keyring.j2 \
      __tmp_inject_files/templates/
    cp \
      roles/resolv_conf/files/NetworkManager-dns-none.conf \
      __tmp_inject_files/files/
    cp -r \
      roles/basic_users \
      roles/cacerts \
      roles/sssd \
      roles/sshd \
      roles/stackhpc.nfs \
      roles/mrlesmithjr.chrony \
      roles/lustre \
      roles/nhc \
      roles/eessi \
      roles/mounts \
      roles/journald \
      __tmp_inject_files/roles/
    cp \
      roles/tuned/tasks/configure.yml \
      __tmp_inject_files/tasks/tuned.yml
  args:
    chdir: "{{ role_path }}/../.."  # this is $APPLIANCES_REPO_ROOT/ansible

- name: Inject files from roles
  ansible.posix.synchronize:
    src: "{{ role_path }}/../../__tmp_inject_files/"
    dest: "/etc/ansible-init/playbooks/"
    archive: true
    rsync_opts:
      - "-p"
      - "--chmod=D770,F644"
    recursive: true
    use_ssh_args: true
  become: true

- name: Cleanup Inject files from roles
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ role_path }}/../../__tmp_inject_files"
    state: absent

- name: Add filter_plugins to ansible.cfg
  ansible.builtin.lineinfile:
    path: /etc/ansible-init/ansible.cfg
    line: "filter_plugins = /etc/ansible-init/filter_plugins"
    state: present
    owner: root
    group: root
    mode: "0644"

- name: Add compute initialisation playbook
  ansible.builtin.copy:
    src: compute-init.yml
    dest: /etc/ansible-init/playbooks/10-compute-init.yml
    owner: root
    group: root
    mode: "0644"
