---
- name: Ensure python3.9 and pip installed
  ansible.builtin.dnf:
    name:
      - python39  # RL8
      - python3-pip  # RL9
  tags: install

- name: Install python mysql client
  vars:
    # use python3.9 to install a recent pymysql version, with fixed SQL injection vulnerability
    ansible_python_interpreter: /usr/bin/python3.9
  ansible.builtin.pip:
    name:
      - pymysql
      - cryptography
    state: present

- name: Create systemd mysql container unit file
  ansible.builtin.template:
    dest: /etc/systemd/system/mysql.service
    src: mysql.service.j2
    mode: "0644"
  register: _mysql_unitfile

- name: Pull container image
  containers.podman.podman_image:
    name: docker.io/library/mysql
    tag: "{{ mysql_tag }}"
  become: true
  become_user: "{{ mysql_podman_user }}"
