---
- hosts: cuda
  gather_facts: true
  tags: cuda_bandwidth
  tasks:
    - name: Run CUDA bandwidth tasks
      ansible.builtin.import_role:
        name: cuda
        tasks_from: bandwidth.yml

- hosts: cuda
  gather_facts: true
  tags: cuda_samples
  tasks:
    - name: Compile cuda samples
      ansible.builtin.import_role:
        name: cuda
        tasks_from: samples.yml
    - name: Prepare output dir
      ansible.builtin.tempfile:
        path: "{{ cuda_samples_path }}/cuda-samples-{{ cuda_version_short }}"
        prefix: "output-"
        state: directory
      register: cuda_samples_output_dir
    - name: Show output dir
      ansible.builtin.debug:
        msg: "cuda samples will output files to: {{ cuda_samples_output_dir.path }}"
    - name: Run cuda samples
      ansible.builtin.command: >-
        python3 ./run_tests.py
          --config test_args.json
          --dir build/bin
          --output {{ cuda_samples_output_dir.path }}
          --parallel {{ cuda_samples_run_tests_concurrency }}
      args:
        chdir: "{{ cuda_samples_path }}/cuda-samples-{{ cuda_version_short }}"
      changed_when: true
