---
# Example usage:
#
# ansible-playbook ansible/adhoc/patch.yaml -e '{
#   "patch_repos": [
#     {
#       "repo_name": "baseos",
#       "subpath": "rocky/9.8/BaseOS/x86_64/os",
#       "timestamp": "20260707T222716",
#       "repo_file": "rocky"
#     }
#   ],
#   "patch_packages": [
#     "kernel"
#   ]
# }'

- name: Enable Ark repos
  hosts: cluster
  become: true
  tasks:
    # Not reusing dnf_repos tooling because it assumes you're upgrading to a snaphost
    # within the same minor version
    - name: Enable repos
      ansible.builtin.yum_repository:
        file: "{{ item.repo_file }}"
        name: "{{ item.repo_name }}"
        baseurl: "{{ appliances_pulp_url }}/pulp/content/{{ item.subpath }}/{{ item.timestamp }}"
        description: "{{ item.repo_name }}"
        username: "{{ dnf_repos_username | default(omit) }}"
        password: "{{ dnf_repos_password | default(omit) }}"
        gpgcheck: "{{ not patch_insecure_disable_gpg_check | default(true) }}"
      loop: "{{ patch_repos }}"

- name: Sync local Pulp server if enabled
  hosts: pulp_server
  tasks:
    - name: Sync pulp
      ansible.builtin.include_role:
        name: pulp_site
        tasks_from: sync.yml
      vars:
        _pulp_site_rpm_info:
          - pulp_repo_name: "{{ repo.repo_name }}-{{ ansible_distribution_major_version }}-{{ repo.timestamp }}"
            pulp_path: "{{ repo.subpath }}"
            pulp_timestamp: "{{ repo.timestamp }}"
      loop: "{{ patch_repos }}"
      loop_control:
        loop_var: repo

- name: Sync local Pulp server if enabled with legacy config (< v2.5)
  hosts: localhost
  tasks:
    - name: Sync pulp
      ansible.builtin.include_role:
        name: pulp_site
        tasks_from: sync.yml
      vars:
        pulp_site_rpm_info:
          - name: "{{ repo.repo_name }}-{{ ansible_distribution_major_version }}-{{ repo.timestamp }}"
            subpath: "{{ repo.subpath }}/{{ repo.timestamp }}"
      loop: "{{ patch_repos }}"
      loop_control:
        loop_var: repo
      when: "{{
          (not 'pulp_server' in groups)
          and (pulp_site_upstream_password is defined and pulp_site_upstream_password | length > 0)
        }}"

- name: Enable Ark repos
  hosts: cluster
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ patch_packages }}"
        state: latest
    - name: Disable repos
      ansible.builtin.yum_repository:
        file: "{{ item.repo_file }}"
        name: "{{ item.repo_name }}"
        baseurl: "{{ appliances_pulp_url }}/pulp/content/{{ item.subpath }}/{{ item.timestamp }}"
        description: "{{ item.repo_name }}"
        gpgcheck: "{{ not patch_insecure_disable_gpg_check | default(true) }}"
        enabled: false
      when: not dnf_repos_enabled | default(false) | bool
      loop: "{{ patch_repos }}"

    - name: Check if reboot required
      ansible.builtin.command:
        cmd: needs-restarting -r
      failed_when: false
      register: _patch_needs_reboot
      changed_when: false

- name: Submit reboot job
  hosts: control[0]
  become: true
  tasks:
    - name: Submit reboot job
      ansible.builtin.command:
        cmd: scontrol reboot ASAP nextstate=RESUME reason="maintenance" ALL
      when: _patch_needs_reboot.rc != 0
      changed_when: true
