# ---
# # NOTE: Requires slurmdbd

- name: Setup OpenSearch
  hosts: opensearch
  tags: opensearch
  become: true
  gather_facts: false # TODO
  tasks:
    - ansible.builtin.import_role:
        name: opensearch
        tasks_from: install.yml
    - ansible.builtin.import_role:
        name: opensearch
        tasks_from: runtime.yml

- name: Setup slurm stats
  hosts: slurm_stats
  tags: slurm_stats
  gather_facts: false # TODO
  tasks:
    - ansible.builtin.include_role:
        name: slurm_stats
        tasks_from: "{{ 'configure.yml' if appliances_mode == 'configure' else 'main.yml' }}"

- name: Deploy filebeat
  hosts: filebeat
  tags: filebeat
  gather_facts: false # TODO
  tasks:
    - ansible.builtin.include_role:
        name: filebeat
        tasks_from: "{{ 'runtime.yml' if appliances_mode == 'configure' else 'main.yml' }}"

- name: Deploy node_exporter
  hosts: node_exporter
  tags: node_exporter
  gather_facts: true # TODO
  gather_subset:
    # can't turn it off entirely and fake via vars.ansible_facts
    # because prometheus uses ansible.builtin.getent which *writes* to ansible_facts
    # which doesn't work if gather_facts is overriden in vars
    - '!all'   # leaves 'min': system, architecture, service_mgr, pkg_mgr, distribution...
    - 'mounts'
  tasks:
    - ansible.builtin.include_role:
        name: prometheus.prometheus.node_exporter
      # vars:
      #   # TODO: move to environments/common/inventory/group_vars/all/defaults.yml?
      #   ansible_facts:
      #     system: Linux
      #     architecture: x86_64
      #     service_mgr: systemd
      #     pkg_mgr: dnf

- name: Deploy Open OnDemand exporter
  hosts: openondemand
  become: true
  gather_facts: false # TODO
  tags:
    - openondemand
    - openondemand_server
  tasks:
    - ansible.builtin.import_role:
        name: openondemand
        tasks_from: exporter.yml

- name: Deploy Slurm exporter
  hosts: slurm_exporter
  become: true
  tags: slurm_exporter
  gather_facts: false # TODO
  tasks:
    - ansible.builtin.include_role:
        name: slurm_exporter
        tasks_from: "{{ 'configure.yml' if appliances_mode == 'configure' else 'main.yml' }}"

- name: Setup core monitoring software
  hosts: prometheus
  tags: prometheus
  gather_facts: true # TODO
  gather_subset:
    # see filebeat comments
    - '!all'   # leaves 'min': system, architecture, service_mgr, pkg_mgr, distribution...
    - processor
  tasks:
    - ansible.builtin.include_role:
        name: prometheus.prometheus.prometheus
      vars:
        prometheus_skip_install: "{{ true if appliances_mode == 'configure' else false }}"

- name: Deploy grafana
  hosts: grafana
  tags: grafana
  gather_facts: false # TODO
  tasks:
    - name: Skip plugin installation in configure mode
      # done during fatimage - can't do this in vars block as that is recursive
      ansible.builtin.set_fact:
        grafana_plugins: "{{ [] if appliances_mode == 'configure' else grafana_plugins }}"
    - name: Ensure Grafana state directory
      ansible.builtin.file:
        path: "{{ grafana_data_dir }}"
        owner: grafana
        group: grafana
        mode: '0755'
        state: directory
      become: true
    - name: Copy Grafana plugins installed in image into persistent grafana state
      ansible.posix.synchronize:
        src: /var/lib/grafana/plugins/ # trailing / means copy contents
        dest: "{{ grafana_data_dir }}/plugins"
        delete: true
        recursive: true
      # Workaround for synchronize module running rsync from deploy host even if targeting remote host,
      # breaking when using SSH bastion
      delegate_to: "{{ inventory_hostname }}"
      become: true
    - ansible.builtin.include_role:
        name: cloudalchemy.grafana
      vars:
        # Internal role used to install dashboards as cloudalchemy role does not support all required options:
        grafana_dashboards: []
    - ansible.builtin.include_role: # done in same play so it can use handlers from cloudalchemy.grafana
        name: grafana-dashboards
      when: "appliances_mode != 'configure'"

- name: Deploy alertmanager
  hosts: alertmanager
  tags: alertmanager
  become: true
  gather_facts: false
  tasks:
    - name: Configure alertmanager
      ansible.builtin.include_role:
        name: prometheus.prometheus.alertmanager
