cluster_net = "stackhpc-ipv4-geneve"
cluster_subnet = "stackhpc-ipv4-geneve-subnet"
vnic_type = "normal"
control_node_flavor = "general.v1.medium"
other_node_flavor = "general.v1.tiny"
state_volume_device_path = "/dev/vdb"
home_volume_device_path = "/dev/vdc"
