name: Launch test deployment and reimage on OpenStack
'on':
  workflow_run:
    workflows:
      - Lint
    types:
      - completed

permissions:
  contents: read
  packages: write
  # To report GitHub Actions status checks
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  stackhpc_check_paths:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
  outputs:
    paths_changed: ${{ toJson(fromJson(steps.filter_on_every.outputs.stackhpc) || fromJson(steps.filter_on_some.outputs.stackhpc)) }}
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Paths matching on every filter rule
      # For safety use the commit of dorny/paths-filter@v3
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
      id: filter_on_every
      with:
        # Filter changed files, 'every' means the file is matched only if it matches all filter rules.
        # NOTE: currently seeing: Warning: Unexpected input(s) 'predicate-quantifier', valid inputs are..
        #       this can be ignored, filtering works as expected.
        predicate-quantifier: 'every'
        list-files: 'json'
        filters: |
          stackhpc:
            - '**'
            - '!dev/**'
            - '!**/*.md'
            - '!.gitignore'
            - '!.github/workflows/**'

    - name: Paths matching on any filter rule
      # For safety use the commit of dorny/paths-filter@v3
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
      id: filter_on_some
      with:
        # Filter changed files, 'some' means the file is matched if any one of the filter rules match.
        # NOTE: currently seeing: Warning: Unexpected input(s) 'predicate-quantifier', valid inputs are..
        #       this can be ignored, filtering works as expected.
        predicate-quantifier: 'some'
        list-files: 'json'
        filters: |
          stackhpc:
            - 'dev/setup-env.sh'
            - '.github/workflows/stackhpc.yml'

    - name: Show paths matching filters
      # Debug step, useful because dorny/paths-filter doesn't work like the conventional 'paths' and 'paths_exclude'
      run: >
        echo '{ "stackhpc_every_files": ${{ steps.filter_on_every.outputs.stackhpc_files }} }' | jq -r '.';
        echo '{ "stackhpc_some_files": ${{ steps.filter_on_some.outputs.stackhpc_files }} }' | jq -r '.';

  stackhpc_launch:
    name: Test deployment and reimage on OpenStack
    needs: stackhpc_check_paths
    if: |
      needs.stackhpc_check_paths.outputs.paths_changed == 'true'
    uses: ./.github/workflows/stackhpc.yml
    secrets: inherit
