name: Launch trivy scan
'on':
  workflow_run:
    workflows:
      - Lint
    types:
      - completed

permissions:
  contents: read
  packages: write
  # To report GitHub Actions status checks
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check_paths:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
  outputs:
    paths_changed: ${{ steps.filter_on_some.outputs.trivyscan }}
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Paths matching on any filter rule
      # For safety use the commit of dorny/paths-filter@v3
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
      id: filter_on_some
      with:
        # Filter changed files, 'some' means the file is matched if any one of the filter rules match.
        # NOTE: currently seeing: Warning: Unexpected input(s) 'predicate-quantifier', valid inputs are..
        #       this can be ignored, filtering works as expected.
        predicate-quantifier: 'some'
        list-files: 'json'
        filters: |
          trivyscan:
            - 'environments/.stackhpc/tofu/cluster_image.auto.tfvars.json'

    - name: Show paths matching filters
      # Debug step, useful because dorny/paths-filter doesn't work like the conventional 'paths' and 'paths_exclude'
      run: >
        echo '{ "paths_changed": ${{ steps.filter_on_some.outputs.paths_changed }} }' | jq -r '.';

  trivy_launch:
    name: Launch trivy scan of image for vulnerabilities
    needs: check_paths
    if: |
      needs.check_paths.outputs.paths_changed == 'true'
    uses: ./.github/workflows/trivyscan.yml
    secrets: inherit
