---

# This file governs the main CI workflow.
# It's the only workflow triggered on push and pull requests,
# it manages the CI workflow as follows:
# 1. Lint the code aborting the workflow if there are linting errors.
# 2. Determine which files have changed and set job outputs accordingly.
# 3. Conditionally run the other workflows based on the changed files:
#    * stackhpc.yml
#    * extra.yml
#    * trivyscan.yml

name: Test on push and pull request

permissions:
  actions: write
  contents: read
  packages: write
  # To report GitHub Actions status checks
  statuses: write
  id-token: write
  # upload trivy scan results
  security-events: write

'on':
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
