---

freeipa_enrol_method: otp

# freeipa_enrol_method = opt:
# no variables

# freeipa_enrol_method = pkinit:
freeipa_servers: [] # list of FQDNs - disables DNS autodiscovery for Kerberos
# node_fqdn:
# freeipa_realm:
freeipa_domain: "{{ freeipa_realm | lower }}"
freeipa_cert_path: "{{ appliances_environment_root }}/freeipa"
freeipa_ca_cert_file: ''
_freeipa_keytab_backup_path: "{{ hostvars[groups['control'].0].appliances_state_dir }}/freeipa/{{ inventory_hostname }}/krb5.keytab"
